config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'

  resources :lists, except: [:show] do
    resources :tasks, except: [:show]
  end

  patch :completed, to: 'tasks#completed'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

    def index
    end
  end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path
    else
      redirect_to new_list_path
    end
  end

  def edit
    @list = List.find_by(id: params[:id])
  end

  def update
    @list = List.find_by(id: params[:id])

    if @list.update(list_params)
      redirect_to lists_path(@list)
    else
      redirect_to edit_list_path(@list)
    end
  end

  def destroy
    @list = List.find_by(id: params[:id])
    if @list.destroy
      redirect_to lists_path
    else
      redirect_to lists_path(@list)
    end
  end

  private

  def list_params
    params.require(:list).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @list = List.includes(:tasks).find_by(id: params[:list_id])
    @tasks = @list.tasks.order("created_at DESC")
    @task = Task.new
    @incompleted_task = Task.where(completed: false)
    @completed_task = Task.where(completed: true)
  end

  def new
    @task = Task.new
    @list = List.find_by(id: params[:list_id])
  end

  def create
    @list = List.find_by(id: params[:list_id])
    @task = Task.new(task_params.merge(list_id: params[:list_id]))

    if @task.save
      flash.now[:success] = "New task created."
      redirect_to list_tasks_path(@list)
    else
      flash.now[:danger] = @task.errors.full_messages
      redirect_to new_list_task_path(@list)
    end
  end

  def edit
    @task = Task.find_by(id: params[:id])
    @list = @task.list
  end

  def update
    @task = Task.find_by(id: params[:id])
    @list = List.find_by(id: params[:list_id])

    if @task.update(task_params)
      flash[:success] = "Updated task."
      redirect_to list_tasks_path(@list, @task)
    else
      flash[:danger] = @task.errors.full_messages
      redirect_to edit_list_task_path(@list, @task)
    end
  end

  def completed

    @task = Task.find_by(id: params[:task_id])
    @list = List.find_by(id: params[:list_id])

    if @task.update_attribute(:completed, true)
    flash[:success] = "Task completed"
    redirect_to list_tasks_path(@list, @task)
    end
  end

  def destroy
    @task = Task.find_by(id: params[:id])
    @list = @task.list

    if @task.destroy
      flash[:success] = "Deleted task."
      redirect_to list_tasks_path(@list)
    end
  end

  private

  def task_params
    params.require(:task).permit(:description, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_messages_helper.rb
module FlashMessagesHelper

  def display_message(value)

    return content_tag(:p, value) unless value.kind_of?(Array)

    content_tag :ul do
      value.collect { |message| content_tag(:li, message, class: 'list-styling') }.join.html_safe
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/landing/index.html.erb
<div class="landing">

  <div class="background">
    <div class="content text-center">
      <h1> The only tool that helps you </h1>
      <h1> GET SHIT DONE </h1>
    </div>
  </div>
  <div class="background2">
    <div class="content text-center">
      <h1> Features </h1>
    </div>
  </div>
  <div class="background3">
    <div class="content text-center">
      <h1> Organise your life right now </h1>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <%= render partial: 'partials/header' %>
    </div>
    <%= render partial: "partials/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<%= form_for(@list, url: list_path(@list), html: { id: "list-update-form" }) do |f| %>
  <h1 class="text-center">
    Edit Lists
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "list_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "list_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update List", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<% @lists.each do |list| %>
  <div class="list">
    <h3><%= link_to list.title, list_tasks_path(list), :class => "title-link-color" %></h3>
    <h5><%= list.description %></h5>
    
    <%= link_to ("Edit"), edit_list_path(list), :class => "btn btn-warning" %>
    <%= link_to ("Delete"), list_path(list), method: :delete, data: { confirm: "Delete?" }, :class => "btn btn-warning" %>
  </div>
<% end %>

app/views/lists/new.html.erb
<%= form_for(@list, url: lists_path, html: { id: "list-create-form" }) do |f| %>
  <h1 class="text-center">
    Create List
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "list_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "list_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create List", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<p><%= @list.description %></p>
<%= link_to "Delete", lists_path(@list), method: :delete, data: { confirm: "Delete?" } %>

app/views/partials/_flash_messages.html.erb
<div id = "flash-messages-container">
  <% flash.each do |k,v| %>
    <section class="flash-messages">
      <div class="alert alert-<%=k%>">
        <button type="button" class="close" data-dismiss="alert" id="close">
          &times;
        </button>
        <div class="message">
          <%= display_message(v) %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="btn btn-default navbar-btn">Sign up</button>
      </a>
      <button type="button" class="btn btn-default navbar-btn">Login</button>
      </a>
    </div>
  </div>
</nav>

app/views/tasks/edit.html.erb
<%= form_for(@task, url: list_task_path(@list), html: { id: "list-update-form" }) do |f| %>
  <h1 class="text-center">
    Edit Tasks
  </h1>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "task_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Task", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% @tasks.each do |task| %>

  <div class="task">
    <h5> <%= task.description %></h5>
    <!-- <h5> <span style="text-decoration: line-through;"> <%= task.description %></span></h5> -->

    <%= link_to ("Completed"), completed_path(list_id: @list.id, task_id: task.id), method: :patch %>
      <p style="opacity: 0.4;"><strike><%= task.description %></strike></p>
    <%= link_to ("Edit"), edit_list_task_path(@list, task), :class => "btn btn-warning" %>
    <%= link_to ("Delete"), list_task_path(@list, task), method: :delete, data: { confirm: "Delete?" }, :class => "btn btn-warning" %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<%= form_for(@task, url: list_tasks_path(@list), html: { id: "task-create-form" }) do |f| %>

  <h1 class="text-center">
    Create Task
  </h1>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "task_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Task", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.description %></h1>

<%= link_to "Delete", list_tasks_path(@task), method: :delete, data: { confirm: "Delete?" } %>